DROP TABLE BIGDATA_ARC_VOLUME_PERM_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_ARC_VOLUME_PERM_S01
(
  "用户ID"  INT(16),
  "年月"    VARCHAR(6),
  "月用电量"  INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_A_RCVBL_FLOW_PM_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_A_RCVBL_FLOW_PM_S01
(
  "用户号"  VARCHAR(16),
  "年月"   VARCHAR(6),
  "实收"   INT,
  "应收"   INT,
  "欠费"   INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_CHANGE_PAYTYPE_PY_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_CHANGE_PAYTYPE_PY_S01
(
  "用户ID"      INT(16),
  "年份"        VARCHAR(4),
  "缴费方式变更次数"  INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_POWER_STEAL_PERY_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_POWER_STEAL_PERY_S01
(
  "用户ID"    INT(16)                          NOT NULL,
  "年份"      VARCHAR(8),
  "违约用电次数"  INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_TS_OR_PRCSCOPE_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_TS_OR_PRCSCOPE_S01
(
  "用户号"   VARCHAR(16),
  "电价名称"  VARCHAR(256),
  "是否分时"  VARCHAR(2),
  "是否阶梯"  CHAR(2)
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIGDATA_USER_INFO_S01
 DROP PRIMARY KEY CASCADE;

DROP TABLE BIGDATA_USER_INFO_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_USER_INFO_S01
(
  "用户ID"      INT(16)                        NOT NULL,
  "客户名称"      VARCHAR(256),
  "电价代码"      VARCHAR(8),
  "地市局编码"     VARCHAR(16),
  "用电性质"      CHAR(1),
  "用电类别"      VARCHAR(256),
  "供电电压"      VARCHAR(256),
  "合同容量"      INT(16,6),
  "负荷类型"      VARCHAR(256),
  "当前是否销户"    VARCHAR(6),
  "城镇用户农村用户"  VARCHAR(256),
  "出账周期"      CHAR(1),
  "行业"        VARCHAR(60),
  "高压低压"      VARCHAR(256),
  "用户号"       VARCHAR(16)
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE BIGDATA_USER_INFO_S1
 DROP PRIMARY KEY CASCADE;

DROP TABLE BIGDATA_USER_INFO_S1 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_USER_INFO_S1
(
  "用户ID"      INT(16)                        NOT NULL,
  "客户名称"      VARCHAR(256),
  "电价代码"      VARCHAR(8),
  "地市局编码"     VARCHAR(16),
  "用电性质"      CHAR(1),
  "用电类别"      VARCHAR(256),
  "供电电压"      VARCHAR(256),
  "合同容量"      INT(16,6),
  "负荷类型"      VARCHAR(256),
  "当前是否销户"    VARCHAR(6),
  "城镇用户农村用户"  VARCHAR(256),
  "出账周期"      CHAR(1),
  "行业"        VARCHAR(60),
  "高压低压"      VARCHAR(256),
  "用户号"       VARCHAR(16),
  "电压"        VARCHAR(8)
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_VOLUME_OF_PRC_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_VOLUME_OF_PRC_S01
(
  CONS_NO  VARCHAR(16),
  YM       VARCHAR(6),
  "一阶电量"   INT,
  "一阶电价"   INT,
  "二阶电量"   INT,
  "二阶电价"   INT,
  "三阶电量"   INT,
  "三阶电价"   INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE BIGDATA_VOLUME_OF_TS_S01 CASCADE CONSTRAINTS;

CREATE TABLE BIGDATA_VOLUME_OF_TS_S01
(
  CONS_NO  VARCHAR(16),
  YM       VARCHAR(6),
  "尖峰电量"   INT,
  "尖峰电价"   INT,
  "峰电量"    INT,
  "峰电价"    INT,
  "平电量"    INT,
  "平电价"    INT,
  "谷电量"    INT,
  "谷电价"    INT,
  "脊骨电量"   INT,
  "脊骨电价"   INT
)
TABLESPACE EPCDAT1
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX INDEX02_BIGDATA_USER_INFO_S01 ON BIGDATA_USER_INFO_S01
("用户号")
LOGGING
TABLESPACE EPCDAT1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INDEX02_BIGDATA_USER_INFO_S1 ON BIGDATA_USER_INFO_S1
("用户号")
LOGGING
TABLESPACE EPCDAT1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INDEX_BIGDATA_USER_INFO_S01 ON BIGDATA_USER_INFO_S01
("用户ID")
LOGGING
TABLESPACE EPCDAT1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX INDEX_BIGDATA_USER_INFO_S1 ON BIGDATA_USER_INFO_S1
("用户ID")
LOGGING
TABLESPACE EPCDAT1
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE BIGDATA_USER_INFO_S01 ADD (
  CONSTRAINT INDEX_BIGDATA_USER_INFO_S01
  PRIMARY KEY
  ("用户ID")
  USING INDEX INDEX_BIGDATA_USER_INFO_S01
  ENABLE VALIDATE);

ALTER TABLE BIGDATA_USER_INFO_S1 ADD (
  CONSTRAINT INDEX_BIGDATA_USER_INFO_S1
  PRIMARY KEY
  ("用户ID")
  USING INDEX INDEX_BIGDATA_USER_INFO_S1
  ENABLE VALIDATE);
