多个步骤
==================
1. 除以ALL_TIME来获得百分比
from ykbz_detail_t2_selectcolumns
select ALL_TIME,PLAN_REPLY_TIME/ALL_TIME,SCENE_RESEARCH_TIME/ALL_TIME,PLAN_CHECK_TIME/ALL_TIME,DATA_CHECK_TIME/ALL_TIME,
PROCESS_CHECK_TIME/ALL_TIME,COMPLETED_ACCEPT_TIME/ALL_TIME, SEND_ELE_TIME/ALL_TIME limit 10;

2. 选择几个列求和,并用来计算百分比
from (
    from ykbz_detail_t2_selectcolumns
    select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
        PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME,
        (PLAN_REPLY_TIME+SCENE_RESEARCH_TIME+PLAN_CHECK_TIME+DATA_CHECK_TIME+PROCESS_CHECK_TIME+COMPLETED_ACCEPT_TIME+SEND_ELE_TIME) as total
        limit 10
) a
select PLAN_REPLY_TIME/total,SCENE_RESEARCH_TIME/total,PLAN_CHECK_TIME/total,DATA_CHECK_TIME/total,
       PROCESS_CHECK_TIME/total,COMPLETED_ACCEPT_TIME/total, SEND_ELE_TIME/total,total limit 10;

3. 选择几个列求和,并用来计算百分比 => 创建和表
CREATE VIEW YKBZ_DETAIL_TRANSFORMED_VIEW AS
select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
        PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME,
        (PLAN_REPLY_TIME+SCENE_RESEARCH_TIME+PLAN_CHECK_TIME+DATA_CHECK_TIME+PROCESS_CHECK_TIME+COMPLETED_ACCEPT_TIME+SEND_ELE_TIME) as total
from ykbz_detail_t2_selectcolumns
;

CREATE TABLE YKBZ_DETAIL_TRANSFORMED AS
select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
        PLAN_REPLY_TIME/total as PLAN_REPLY_TIME, SCENE_RESEARCH_TIME/total as SCENE_RESEARCH_TIME,
        PLAN_CHECK_TIME/total as PLAN_CHECK_TIME, DATA_CHECK_TIME/total as DATA_CHECK_TIME,
        PROCESS_CHECK_TIME/total as PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME/total as COMPLETED_ACCEPT_TIME,
        SEND_ELE_TIME/total as SEND_ELE_TIME,
        total
from YKBZ_DETAIL_TRANSFORMED_VIEW
;

4. 选择用来聚类的列
CREATE TABLE YKBZ_DETAIL_FOR_KMEANS AS
select PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME
from YKBZ_DETAIL_TRANSFORMED
;

CREATE TABLE YKBZ_DETAIL_FOR_KMEANS_tab
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
AS
select PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME
from YKBZ_DETAIL_TRANSFORMED
;

此时,hdfs中的存储路径为 /user/hive/warehouse/ykbz_detail_for_kmeans_tab

直接在hive中创建SEQUENCEFILE失败.
CREATE TABLE YKBZ_DETAIL_FOR_KMEANS_sequence_file_table STORED AS SEQUENCEFILE
select PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME
from YKBZ_DETAIL_FOR_KMEANS
;

5.

能用一条语句实现吗?
==================

CREATE TABLE YKBZ_DETAIL_TRANSFORMED_VIEW AS
(
    from (
        select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
            PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME,
            (PLAN_REPLY_TIME+SCENE_RESEARCH_TIME+PLAN_CHECK_TIME+DATA_CHECK_TIME+PROCESS_CHECK_TIME+COMPLETED_ACCEPT_TIME+SEND_ELE_TIME) as total
        from ykbz_detail_t2_selectcolumns limit 10
        ) a
    select a.PLAN_REPLY_TIME/a.total,a.SCENE_RESEARCH_TIME/a.total,a.PLAN_CHECK_TIME/a.total,a.DATA_CHECK_TIME/a.total,
           a.PROCESS_CHECK_TIME/a.total,a.COMPLETED_ACCEPT_TIME/a.total, a.SEND_ELE_TIME/a.total,a.total
);

CREATE TABLE YKBZ_DETAIL_TRANSFORMED_VIEW AS
(

    select a.PLAN_REPLY_TIME/a.total,a.SCENE_RESEARCH_TIME/a.total,a.PLAN_CHECK_TIME/a.total,a.DATA_CHECK_TIME/a.total,
           a.PROCESS_CHECK_TIME/a.total,a.COMPLETED_ACCEPT_TIME/a.total, a.SEND_ELE_TIME/a.total,a.total
        from (
            select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
                PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME,
                (PLAN_REPLY_TIME+SCENE_RESEARCH_TIME+PLAN_CHECK_TIME+DATA_CHECK_TIME+PROCESS_CHECK_TIME+COMPLETED_ACCEPT_TIME+SEND_ELE_TIME) as total
            from ykbz_detail_t2_selectcolumns limit 10
            ) a
);


CREATE TABLE YKBZ_DETAIL_TRANSFORMED_VIEW AS
from (
    select YEKUOGDH,GONGDANCJRQ,GONGDIANDW_DS,GONGDIANDW_XQ,YONGHUMC,YONGHUBZRL,YONGHUYYRL,DIANYADJ,YONGDIANLB,
        PLAN_REPLY_TIME, SCENE_RESEARCH_TIME, PLAN_CHECK_TIME, DATA_CHECK_TIME, PROCESS_CHECK_TIME, COMPLETED_ACCEPT_TIME, SEND_ELE_TIME,
        (PLAN_REPLY_TIME+SCENE_RESEARCH_TIME+PLAN_CHECK_TIME+DATA_CHECK_TIME+PROCESS_CHECK_TIME+COMPLETED_ACCEPT_TIME+SEND_ELE_TIME) as total
    from ykbz_detail_t2_selectcolumns limit 10
    ) a
select a.PLAN_REPLY_TIME/a.total,a.SCENE_RESEARCH_TIME/a.total,a.PLAN_CHECK_TIME/a.total,a.DATA_CHECK_TIME/a.total,
       a.PROCESS_CHECK_TIME/a.total,a.COMPLETED_ACCEPT_TIME/a.total, a.SEND_ELE_TIME/a.total,a.total
;
